### ISSUE TITLE
IndexOutOfRangeExeption

### ISSUE THREAD

**Issue by headblockhead** [miguel12345/UnityWireframeRenderer#3]
![image](https://user-images.githubusercontent.com/26520767/108507201-dd268880-72b1-11eb-946b-b9aa7e143e0b.png)
![image](https://user-images.githubusercontent.com/26520767/108507271-f9c2c080-72b1-11eb-9e64-2287b7e7d5e9.png)
![image](https://user-images.githubusercontent.com/26520767/108507333-1101ae00-72b2-11eb-901d-50af14f1858c.png)
![image](https://user-images.githubusercontent.com/26520767/108507421-3393c700-72b2-11eb-96f1-49459a5de2a5.png)

**Comment by islent** [comment]
Got same error here, but easy to resolve: 

Just delete any code blocks related to `processedBoneWeigths` and everything works!

Have fun!

**Comment by headblockhead** [comment]
Thanks!
